// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcsg.trapfields.domain;

import com.bcsg.trapfields.domain.BlockedIp;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BlockedIp_Roo_Configurable {
    
    declare @type: BlockedIp: @Configurable;
    
}
