// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcsg.trapfields.domain;

import com.bcsg.trapfields.domain.BlockedIp;

privileged aspect BlockedIp_Roo_JavaBean {
    
    public String BlockedIp.getIpAddress() {
        return this.ipAddress;
    }
    
    public void BlockedIp.setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
}
