// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcsg.trapfields.domain;

import com.bcsg.trapfields.domain.BlockedIp;
import com.bcsg.trapfields.domain.BlockedIpDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BlockedIpDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BlockedIpDataOnDemand: @Component;
    
    private Random BlockedIpDataOnDemand.rnd = new SecureRandom();
    
    private List<BlockedIp> BlockedIpDataOnDemand.data;
    
    public BlockedIp BlockedIpDataOnDemand.getNewTransientBlockedIp(int index) {
        BlockedIp obj = new BlockedIp();
        setIpAddress(obj, index);
        return obj;
    }
    
    public void BlockedIpDataOnDemand.setIpAddress(BlockedIp obj, int index) {
        String ipAddress = "ipAddress_" + index;
        obj.setIpAddress(ipAddress);
    }
    
    public BlockedIp BlockedIpDataOnDemand.getSpecificBlockedIp(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BlockedIp obj = data.get(index);
        Long id = obj.getId();
        return BlockedIp.findBlockedIp(id);
    }
    
    public BlockedIp BlockedIpDataOnDemand.getRandomBlockedIp() {
        init();
        BlockedIp obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return BlockedIp.findBlockedIp(id);
    }
    
    public boolean BlockedIpDataOnDemand.modifyBlockedIp(BlockedIp obj) {
        return false;
    }
    
    public void BlockedIpDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BlockedIp.findBlockedIpEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BlockedIp' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BlockedIp>();
        for (int i = 0; i < 10; i++) {
            BlockedIp obj = getNewTransientBlockedIp(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
