// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcsg.trapfields.domain;

import com.bcsg.trapfields.domain.BlockedIp;
import com.bcsg.trapfields.domain.BlockedIpDataOnDemand;
import com.bcsg.trapfields.domain.BlockedIpIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BlockedIpIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BlockedIpIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BlockedIpIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BlockedIpIntegrationTest: @Transactional;
    
    @Autowired
    BlockedIpDataOnDemand BlockedIpIntegrationTest.dod;
    
    @Test
    public void BlockedIpIntegrationTest.testCountBlockedIps() {
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", dod.getRandomBlockedIp());
        long count = BlockedIp.countBlockedIps();
        Assert.assertTrue("Counter for 'BlockedIp' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BlockedIpIntegrationTest.testFindBlockedIp() {
        BlockedIp obj = dod.getRandomBlockedIp();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to provide an identifier", id);
        obj = BlockedIp.findBlockedIp(id);
        Assert.assertNotNull("Find method for 'BlockedIp' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BlockedIp' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BlockedIpIntegrationTest.testFindAllBlockedIps() {
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", dod.getRandomBlockedIp());
        long count = BlockedIp.countBlockedIps();
        Assert.assertTrue("Too expensive to perform a find all test for 'BlockedIp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BlockedIp> result = BlockedIp.findAllBlockedIps();
        Assert.assertNotNull("Find all method for 'BlockedIp' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BlockedIp' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BlockedIpIntegrationTest.testFindBlockedIpEntries() {
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", dod.getRandomBlockedIp());
        long count = BlockedIp.countBlockedIps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BlockedIp> result = BlockedIp.findBlockedIpEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BlockedIp' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BlockedIp' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BlockedIpIntegrationTest.testFlush() {
        BlockedIp obj = dod.getRandomBlockedIp();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to provide an identifier", id);
        obj = BlockedIp.findBlockedIp(id);
        Assert.assertNotNull("Find method for 'BlockedIp' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBlockedIp(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BlockedIp' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlockedIpIntegrationTest.testMergeUpdate() {
        BlockedIp obj = dod.getRandomBlockedIp();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to provide an identifier", id);
        obj = BlockedIp.findBlockedIp(id);
        boolean modified =  dod.modifyBlockedIp(obj);
        Integer currentVersion = obj.getVersion();
        BlockedIp merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BlockedIp' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlockedIpIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", dod.getRandomBlockedIp());
        BlockedIp obj = dod.getNewTransientBlockedIp(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BlockedIp' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BlockedIp' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BlockedIpIntegrationTest.testRemove() {
        BlockedIp obj = dod.getRandomBlockedIp();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BlockedIp' failed to provide an identifier", id);
        obj = BlockedIp.findBlockedIp(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BlockedIp' with identifier '" + id + "'", BlockedIp.findBlockedIp(id));
    }
    
}
